# Step 2

seed_list: [0,1,2]
world_size: 2
batch_size: 8
num_workers: 4
data_path: 
save_path: /home/elicer/OSPO/examples/step2
ckpt_path:
model_path: /home/elicer/checkpoints/Janus-Pro-7B
cache_dir: /home/elicer/checkpoints/hf_cache
generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 512

