# Step 2

s_idx:
e_idx:
data_path:
batch_size:
num_workers: 
seed_list:
world_size:
save_path:
ckpt_path:
model_path: /nas2/checkpoints/Janus-Pro-7B
cache_dir: /nas2/checkpoints/hf_cache_yj
generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 512