# Step 2

seed_list: [0,1,2]
world_size: 
batch_size: 
num_workers: 
data_path: 
save_path: ./examples/step2
ckpt_path:
model_path: ./checkpoints/Janus-Pro-7B
cache_dir: ./checkpoints/hf_cache
generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 512