# Step 3

seed_list: [0,1,2]
world_size:
batch_size: 
num_workers:
data_path: 
save_path: ./examples/step3
ckpt_path:
model_path: ./checkpoints/Janus-Pro-7B
cache_dir: ./checkpoints/hf_cache
generation_config: 
  parallel_size: 1
  temperature: 1.0
  cfg_weight: 5.0