# Step 1

seed: 42
world_size: 1
batch_size: 1
num_workers: 4
save_path: /home/elicer/OSPO/example/step1
ckpt_path: 
model_path: /home/elicer/checkpoints/Janus-Pro-7B
cache_dir: /home/elicer/checkpoints/hf_cache
max_len: 10 # sample num per category
category: 
category_num:
  attribute1_color: 2
  attribute1_shape: 2
  attribute1_texture: 2 
  attribute2: 4
  layout1: 4
  layout2: 3
  layout3: 3
  non-spatial: 10
  complex: 10
generation_config:
  do_sample: True
  temperature: 1.3
  max_new_tokens: 256