# Step 4

seed: 42
world_size: 
batch_size:  
num_workers: 
data_path: 
image_path: ./exampls/step3
save_path: ./examples/step4
ckpt_path:
model_path: ./checkpoints/Janus-Pro-7B
cache_dir: ./checkpoints/hf_cache
generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 0.8
  top_p: 0.9
  max_new_tokens: 256