# Step 3

seed_list: [0, 1, 2]
world_size: 2
batch_size: 8
num_workers: 4
data_path: 
save_path: /home/elicer/OSPO/example/step3
ckpt_path:
model_path: /home/elicer/checkpoints/Janus-Pro-7B
cache_dir: /home/elicer/checkpoints/hf_cache
generation_config: 
  parallel_size: 1
  temperature: 1.0
  cfg_weight: 5.0