# Step 1

seed: 42
world_size: 1
batch_size: 1
num_workers: 
save_path: ./examples/step1
ckpt_path: 
model_path: ./checkpoints/Janus-Pro-7B
cache_dir: ./checkpoints/hf_cache
max_len: 4000 # sample num per category
category: 
category_num:
  attribute1_color: 666 
  attribute1_shape: 667
  attribute1_texture: 667
  attribute2: 2000
  layout1: 2000
  layout2: 1000
  layout3: 1000
  non-spatial: 4000
  complex: 4000
generation_config:
  do_sample: True
  temperature: 1.3 
  max_new_tokens: 256