# Step 1

# CUDA_VISIBLE_DEVICES=1 python /home/elicer/OSPO/ospo/step1_generate.py

seed: 42
world_size: 1
batch_size: 1
save_path: /home/elicer/OSPO/data_example/step1
ckpt_path: 
model_path: /home/elicer/checkpoints/Janus-Pro-7B
cache_dir: /home/elicer/checkpoints/hf_cache
category: complex # object, color, shape, texture, spatial, non-spatial, complex
max_len: 10
generation_config:
  do_sample: True
  temperature: 1.3
  max_new_tokens: 256
category_num:
  attribute1_color: 2
  attribute1_shape: 2
  attribute1_texture: 2 
  attribute2: 4
  layout1: 4
  layout2: 3
  layout3: 3
  non-spatial: 10
  complex: 10
